config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users
  get 'admin' => 'admin/books#index'
  get 'admin.:id' => 'admin/books#show'
  get 'admin/new' => 'admin/books#new'
  post 'admin' => 'admin/books#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
  scope :tagged_recommended, -> { joins(:tags).where(tags: {name: 'recommended'}) }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
end

app/controllers/admin/books_controller.rb
# coding: utf-8
class Admin::BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    params[:book] = {
      "title" => "新しい本",
      "author" => "新しい作者",
    }
    Book.new(params[:book])
  end

  def show
    @book = Book.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %w(show edit update destroy)

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :department)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
      <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :outline %>
    <%= form.text_area :outline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Outline</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.outline %></td>
      <td><%= link_to 'Show', admin_path(book.id) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', admin_new_path %>

app/views/admin/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Book', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :department %><br>
  <%= f.text_field :department %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>利用者一覧</h1>

<table>
  <thead>
    <tr>
      <th>氏名</th>
      <th>部署</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= user.department %></td>
      <td>
        <%= link_to '編集', edit_user_path(user) %>
        <%= link_to '削除', user_path(user), method: 'DELETE' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新規作成', new_user_path %>

app/views/users/new.html.erb
<h1>新規利用者</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>氏名:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>部署:</strong>
  <%= @user.department %>
</p>

<%= link_to 'Back', users_path %>